spring:
  datasource:
    test01:
      url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      minPoolSize:  3
      maxPoolSize:  25
      maxLifetime:  20000
      borrowConnectionTimeout:  30
      loginTimeout: 30
      maintenanceInterval:  60
      maxIdleTime:  60

    test02:
      url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      minPoolSize:  3
      maxPoolSize:  25
      maxLifetime:  20000
      borrowConnectionTimeout:  30
      loginTimeout: 30
      maintenanceInterval:  60
      maxIdleTime:  60
